/*
 * CarouselMenu.java
 *
 * Created on January 12, 2007, 6:13 AM
 *
 * Copyright 2006-2007 Nigel Hughes
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at http://www.apache.org/
 * licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

package com.blogofbug.examples;

import cascade.Demo;
import com.blogofbug.examples.yahooimagesearch.YahooImageSearch;
import com.blogofbug.examples.yahooimagesearch.YahooImageSearcher;
import com.blogofbug.swing.components.AbstractCarouselMenuAction;
import com.blogofbug.swing.components.EffectsPanel;
import com.blogofbug.swing.components.JCarosel;
import com.blogofbug.swing.components.JCarouselMenu;
import com.blogofbug.swing.components.SystemNavigator;
import com.blogofbug.swing.components.effects.Effect;
import com.blogofbug.swing.components.effects.EffectSequence;
import com.blogofbug.swing.components.effects.FadeEffect;
import com.blogofbug.swing.components.effects.ScrollImage;
import com.blogofbug.tests.JBookPanelTest;
import com.blogofbug.utility.ImageUtilities;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.net.URL;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author  nigel
 */
public class CarouselMenu extends javax.swing.JFrame {
    EffectsPanel        effectsPanel = new EffectsPanel(false);
    
    
    
    /** Creates new form CarouselMenu */
    public CarouselMenu() {
        initComponents();
        this.setResizable(false);
        final JCarouselMenu carousel = new JCarouselMenu();
        carousel.setBackground(Color.BLACK,new Color(0,0,1      ));
        this.getContentPane().setLayout(new BorderLayout());
        carousel.setPreferredSize(new Dimension(400,400));
        
        //carousel.add(new ActionCarouselLayout(CaroselFinal.class.getResource("/com/blogofbug/examples/images/Carousel Layout.png"),"Carousel Layout"));
        //carousel.add(new ActionCarouselComponent(CaroselFinal.class.getResource("/com/blogofbug/examples/images/Carousel Component.png"),"Carousel Component"));
        //carousel.add(new ActionDock(CaroselFinal.class.getResource("/com/blogofbug/examples/images/Dock.png"),"Glass Pane Dock Demo"));
        

        addAction(carousel,new ActionCarouselFinal(CaroselFinal.class.getResource("/com/blogofbug/examples/images/Full Carousel.png"),"Java Carousel"),0);
        addAction(carousel,new ActionLayeredDock(CaroselFinal.class.getResource("/com/blogofbug/examples/images/Dock.png"),"Java Dock"),200);
        addAction(carousel,new ActionYahooImageSearch(),400);
        addAction(carousel,new ActionComponentEffects(),400);
        addAction(carousel,new ActionSplicedPanels(),400);
        addAction(carousel,new ActionTimerTest(),400);
        addAction(carousel,new ActionCascade(CaroselFinal.class.getResource("/com/blogofbug/examples/images/Cascade.png"),"Cascade Demo"),500);
        addAction(carousel,new ActionAcknowledgements(CaroselFinal.class.getResource("/com/blogofbug/examples/images/Acknowledgements.png"),"Acknowledgements"),600);

              
        
        carousel.setSelectedIndex(0);
        this.setGlassPane(effectsPanel);
        effectsPanel.setVisible(true);
        this.getContentPane().add(carousel,BorderLayout.CENTER);
        this.setSize(600,400);
        
    }
    
    public void addAction(final JCarouselMenu carousel, final AbstractCarouselMenuAction action, int delay){
        carousel.add(action);
//        SwingBugUtilities.invokeAfter(new Runnable() {
//            public void run() {
//                carousel.add(action);
//            }
//        },delay);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BlogOfBug Demo Library");
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarouselMenu().setVisible(true);
            }
        });
    }
    
    public class ActionCarouselLayout extends AbstractCarouselMenuAction{
        public ActionCarouselLayout(URL image, String label){
            super(image,label);
        }
        public void actionPerformed(ActionEvent actionEvent) {
            new CaroselLayoutManager().setVisible(true);
        }
    }
    
    public class ActionCascade extends AbstractCarouselMenuAction{
        public ActionCascade(URL image, String label){
            super(image,label);
        }
        public void actionPerformed(ActionEvent actionEvent) {
            new Demo().setVisible(true);
        }
    }
    
    public class ActionCarouselComponent extends AbstractCarouselMenuAction{
        public ActionCarouselComponent(URL image, String label){
            super(image,label);
        }
        public void actionPerformed(ActionEvent actionEvent) {
            new CaroselComponentExample().setVisible(true);
        }
    }
    
    public class ActionCarouselFinal extends AbstractCarouselMenuAction{
        public ActionCarouselFinal(URL image, String label){
            super(image,label);
        }
        public void actionPerformed(ActionEvent actionEvent) {
            new CaroselFinal().setVisible(true);
        }
    }
    
    public class ActionDock extends AbstractCarouselMenuAction{
        public ActionDock(URL image, String label){
            super(image,label);
        }
        public void actionPerformed(ActionEvent actionEvent) {
            new DockFinalDemo().setVisible(true);
        }
    }
    
    public class ActionLayeredDock extends AbstractCarouselMenuAction{
        public ActionLayeredDock(URL image, String label){
            super(image,label);
        }
        public void actionPerformed(ActionEvent actionEvent) {
            new DockLayeredPane().setVisible(true);
        }
    }
    
    public class ActionAcknowledgements extends AbstractCarouselMenuAction{
        public String acknowledgements[] = new String[]{
            "BlogOfBug and Swing-Bug are intended to publically disseminate code and information to promote the use of Java on the Desktop and dispell the myths surrounding performance and capability. None of this would have been possible without the contribution of ideas, code, and resources from the following people or orginizations:",
            " ",
            "Romain Guy: Original source code for the image reflections, and inspiration",
            " ",
            "Jerry Huxtable: The Filters library used in swing-bug for the filers. Superb work http://www.jhlabs.com/",
            " ",
            "Pieter-Jan Savat: The amazing JBookPanel component that is extended in this library. http://jroller.com/page/pieterjan.",
            " ",
            "Krill Grouchnikov: Code contributor and ideas",
            " ",
            "Sebastient Charpentier: Bug (no pun) spotting and his viewport code hit the nail on the head!",
            " ",
            "Most Icons: Eugen Buzuk from www.IconDrawer.com buz@icondrawer.com",
            " ",
            "Image Searching API provided by Yahoo! Web-Services - http://developer.yahoo.net/about/",
            " ",
            "http://java.sun.com/"
        };
        
        public ActionAcknowledgements(URL image, String label){
            super(image,label);
        }
        public void actionPerformed(ActionEvent actionEvent) {
            BufferedImage image = ImageUtilities.renderTextToImage(new Font("Arial",Font.PLAIN,24),Color.WHITE,acknowledgements,effectsPanel.getWidth()-40);
            
            effectsPanel.addEffect(new EffectSequence( new Effect[] {
                new FadeEffect(Color.BLACK,0.0f,0.75f,effectsPanel),
                new ScrollImage(new Color(0,0,0,196), image, effectsPanel),
                new FadeEffect(Color.BLACK,0.75f,0.0f,effectsPanel)}
            ));
        }
    }
    
    public class ActionQuit extends AbstractCarouselMenuAction{
        public ActionQuit(URL image, String label){
            super(image,label);
        }
        public void actionPerformed(ActionEvent actionEvent) {
            if (JOptionPane.showConfirmDialog(null,"Are you sure you want to quit?","BlogOfBug",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
                System.exit(0);
            }
        }
    }
    
    public class ActionSplicedPanels extends AbstractCarouselMenuAction{
        public ActionSplicedPanels(){
            super(ActionSplicedPanels.class.getResource("/com/blogofbug/examples/images/dna.png"),"Spliced Panels");
        }
        public void actionPerformed(ActionEvent actionEvent) {
//            new SplicedDemo().setVisible(true);
            JFrame wibble    = new JFrame();
            wibble.getContentPane().setLayout(new BorderLayout());
            wibble.getContentPane().add(new SystemNavigator());
            wibble.setSize(600,400);
            wibble.setLocation(100, 100);
            wibble.setVisible(true);
        }
    }
    
    public class ActionComponentEffects extends AbstractCarouselMenuAction{
        public ActionComponentEffects(){
            super(ActionComponentEffects.class.getResource("/com/blogofbug/examples/images/swingpp.png"),"Swing++");
        }
        public void actionPerformed(ActionEvent actionEvent) {
            new SwingPlusPlus().setVisible(true);
        }
    }

    public class ActionTimerTest extends AbstractCarouselMenuAction{
        public ActionTimerTest(){
            super(ActionComponentEffects.class.getResource("/com/blogofbug/examples/images/book.png"),"JBook Panel Demo");
        }
        public void actionPerformed(ActionEvent actionEvent) {
            JBookPanelTest.main(null);
        }
    }    

    public class ActionYahooImageSearch extends AbstractCarouselMenuAction{
        public ActionYahooImageSearch(){
            super(ActionComponentEffects.class.getResource("/com/blogofbug/examples/images/image-search.png"),"Image Search Demo");
        }
        public void actionPerformed(ActionEvent actionEvent) {
            new YahooImageSearcher().setVisible(true);
        }
    }        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    
}
