/*
 * SplicedDemo.java
 *
 * Created on October 21, 2007, 6:05 PM
 */

package com.blogofbug.examples;

import com.blogofbug.swing.components.SplicedNavigator;

/**
 *
 * @author  nigel
 */
public class SplicedDemo extends javax.swing.JFrame {
    
    /** Creates new form SplicedDemo */
    public SplicedDemo() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        splicedPane1 = new com.blogofbug.swing.components.SplicedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(splicedPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplicedDemo().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.blogofbug.swing.components.SplicedPane splicedPane1;
    // End of variables declaration//GEN-END:variables
    
}
