/*
 * NavigateSystem.java
 *
 * Created on October 21, 2007, 5:58 PM
 */

package com.blogofbug.swing.components;

import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author  nigel
 */
public class SystemNavigator extends javax.swing.JPanel {
    private NavigableSystem     system = null;
    private DefaultListModel    rootNodes = new DefaultListModel();
    
    /** Creates new form NavigateSystem */
    public SystemNavigator() {
        initComponents();
        rootsList.setModel(rootNodes);
        rootsList.setCellRenderer(new DefaultNavigationNodeCellRenderer());
        setSystem(new FileSystemNavigable());
    }
    
    /**
     * Sets the system being navigated, updates roots and sets the starting
     * node to be the default root node.
     * 
     * @param system The system to be navigated
     */
    public void setSystem(NavigableSystem system){
        this.system = system;
        
        List<NavigationNode> roots = system.getRoots();
        rootNodes.removeAllElements();
        
        for (NavigationNode root : roots){
            rootNodes.addElement(root);
        }
        rootsList.setSelectedIndex(0);
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        rootsList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        navigator = new com.blogofbug.swing.components.SplicedNavigator();

        setLayout(new java.awt.BorderLayout(4, 4));

        rootsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        rootsList.setMaximumSize(new java.awt.Dimension(200, 85));
        rootsList.setMinimumSize(new java.awt.Dimension(80, 85));
        rootsList.setPreferredSize(new java.awt.Dimension(120, 85));
        rootsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                rootsListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(rootsList);

        add(jScrollPane1, java.awt.BorderLayout.WEST);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setViewportView(navigator);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void rootsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_rootsListValueChanged
        NavigationNode selectedRoot = (NavigationNode) rootsList.getSelectedValue();
        
        navigator.setNode(selectedRoot);
        navigator.refreshContents();
    }//GEN-LAST:event_rootsListValueChanged
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.blogofbug.swing.components.SplicedNavigator navigator;
    private javax.swing.JList rootsList;
    // End of variables declaration//GEN-END:variables
    
}
