package de.fherfurt.imagecompare.components;

import java.awt.BorderLayout;
import java.awt.Color;

import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

import com.blogofbug.examples.CaroselFinal;
import com.blogofbug.swing.components.JCarosel;
import com.jgoodies.looks.plastic.Plastic3DLookAndFeel;

import de.fherfurt.imagecompare.ResourceHandler;

public class MainFrame extends JFrame {

	private static final long serialVersionUID = 1L;
	
	public MainFrame() {
		super("Sirius Client");
		try {
			UIManager.installLookAndFeel("JGoodies Windows LaF",
					"com.jgoodies.looks.windows.WindowsLookAndFeel");
			UIManager.installLookAndFeel("JGoodies Plastic LaF",
					"com.jgoodies.looks.plastic.PlasticLookAndFeel");
			UIManager.installLookAndFeel("JGoodies Plastic3D LaF",
					"com.jgoodies.looks.plastic.Plastic3DLookAndFeel");
			UIManager.installLookAndFeel("JGoodies PlasticXP LaF",
					"com.jgoodies.looks.plastic.PlasticXPLookAndFeel");
//			PlasticLookAndFeel.setPlasticTheme(new DarkStar());
//			PlasticLookAndFeel.setPlasticTheme(new Silver());
//			PlasticLookAndFeel.setPlasticTheme(new SkyGreen());
//			PlasticLookAndFeel.setPlasticTheme(new SkyBlue());
			
			UIManager.setLookAndFeel(new Plastic3DLookAndFeel());
			
		} catch (Exception e1) {
			final JDialog jd = new JDialog();
			JOptionPane.showMessageDialog(jd, e1.getMessage(), "Exception",
					JOptionPane.ERROR_MESSAGE);
		}

		SwingUtilities.updateComponentTreeUI(this);
//		this.setSize(800, 600);
		pack();
		this.setExtendedState(MAXIMIZED_BOTH);
		this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		this.getRootPane().setJMenuBar(new ImageCompareMenu(this));
		this.setLayout(new BorderLayout());
		this.add(new ImageCompareToolBar(), BorderLayout.NORTH);
		
		JPanel startPanel = new JPanel();
		startPanel.setBackground(Color.WHITE);
		JLabel logolabel = new JLabel(new ImageIcon("resources/icons/" + ResourceHandler.getInstance().getIcons().getString("logo")));
		startPanel.add(logolabel);
		
		initComponents();
        JCarosel carosel = new JCarosel(100);
        carosel.setBackground(new Color(50,10,10),Color.BLACK);
    
        carosel.add(CaroselFinal.class.getResource("/com/blogofbug/examples/images/bug256x256.png").toString(),"Swing-Bug");
        carosel.add(CaroselFinal.class.getResource("/com/blogofbug/examples/images/swingpp.png").toString(),"Duke's Den");
        carosel.add(CaroselFinal.class.getResource("/com/blogofbug/examples/images/Full Carousel.png").toString(),"JCarousel 0.4");
        carosel.add(CaroselFinal.class.getResource("/com/blogofbug/examples/images/Cascade.png").toString(),"Cascade Demonstration");
        carosel.add(CaroselFinal.class.getResource("/com/blogofbug/examples/images/Dock.png").toString(),"Docks Rock");
        carosel.add(CaroselFinal.class.getResource("/com/blogofbug/examples/images/Quit.png").toString(),"Quit It Bozo");    
        carosel.add(CaroselFinal.class.getResource("/com/blogofbug/examples/images/Acknowledgements.png").toString(),"Thanks to You!");    
	
        JSplitPane splitpane = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT,
				carosel, startPanel);
		splitpane.setBorder(BorderFactory.createEmptyBorder());
		splitpane.setDividerLocation(0.8);
		
		this.add(splitpane, BorderLayout.CENTER);

		this.setVisible(true);
	
	}

	public static void main(String[] args) {
		new MainFrame();
	}
	
	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JCarosel Final Demo");
        pack();
    }// </editor-fold>//GEN-END:initComponents
	
}